apiVersion: apps/v1
kind: Deployment
metadata:
  name: sb-app-deployment
  labels:
    app: sb-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sb-app-docker
  template:
    metadata:
      labels:
        app: sb-app-docker
    spec:
      containers:
      - name: sb-app-docker
        image: 172.30.1.1:5000/sb-example/sb-app-docker:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: sb-app-service
  labels:
    app: sb-app-service
spec:
  type: ClusterIP
  ports:
  - name: 8080-tcp
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: sb-app-docker
