apiVersion: v1
kind: ReplicationController
metadata:
  name: sb-app-replica
  labels:
    app: sb-app-replica
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sb-app-pod
    spec:
      containers:
      - name: sb-app-docker
        image: quay.io/dav1dli/sb-app-docker:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sb-app-service
  labels:
    app: sb-app-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
  type: NodePort
  selector:
    app: sb-app-pod
