apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.name | quote }}
  annotations:
    description: Exposes to external access an app service
spec:
  host: {{ .Values.application_domain | quote }}
  to:
    kind: Service
    name: {{ .Values.name | quote }}
